-- Create sub_pages table if not exists
CREATE TABLE IF NOT EXISTS `sub_pages` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `page_key` VARCHAR(50) NOT NULL UNIQUE,
    `title` VARCHAR(255) NOT NULL,
    `content` MEDIUMTEXT DEFAULT NULL,
    `image` VARCHAR(255) DEFAULT NULL,
    `meta_title` VARCHAR(255) DEFAULT NULL,
    `meta_description` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed default values if empty
INSERT INTO `sub_pages` (`page_key`, `title`, `content`, `image`, `meta_title`, `meta_description`) VALUES
('about', 'Giới thiệu', '<h2>ThuongLo<br><span class="highlight">Nguồn Hàng Gốc</span> &amp; <span class="highlight">Tự Động Hóa Logistics</span></h2><p>Nền tảng tiên phong cung cấp các gói dữ liệu nhà cung cấp độc quyền và giải pháp vận chuyển thông minh. Chúng tôi bảo vệ tài sản thông tin của bạn bằng công nghệ mã hóa hiện đại, đồng thời tự động hóa quy trình từ thanh toán đến bàn giao dữ liệu chỉ trong vài giây.</p><h3>Kho Nguồn Hàng Độc Quyền</h3><p>Thượng Lộ cung cấp các gói dữ liệu nhà máy, xưởng sản xuất đã qua kiểm duyệt kỹ lưỡng. Là "vũ khí bí mật" giúp bạn tối ưu biên lợi nhuận ngay từ khâu nhập hàng.</p><h3>Công Nghệ Chống Sao Chép</h3><p>Hệ thống của chúng tôi tích hợp các lớp bảo mật cấp cao, ngăn chặn hành vi chia sẻ trái phép hoặc bán lại, đảm bảo lợi thế cạnh tranh độc tôn cho chủ sở hữu gói.</p><h3>Thanh Toán &amp; Kích Hoạt Tự Động</h3><p>Loại bỏ quy trình xác nhận thủ công chậm chạp. Với Thượng Lộ, ngay sau khi quét QR thanh toán, hệ thống Logistics được kích hoạt và kho dữ liệu được mở khóa tự động 100%.</p>', NULL, 'Giới thiệu về Thuong Lo - Nguồn hàng gốc & Logistics', 'Nền tảng tiên phong cung cấp các gói dữ liệu nhà cung cấp độc quyền và giải pháp vận chuyển thông minh Thượng Lộ.'),
('faq', 'Câu hỏi thường gặp', '<h3>Đơn hàng &amp; Thanh toán</h3><p><strong>Làm thế nào để đặt hàng trên ThuongLo?</strong><br>Bạn có thể đặt hàng trực tiếp trên website bằng cách chọn sản phẩm, thêm vào giỏ hàng và tiến hành thanh toán. Chúng tôi hỗ trợ nhiều hình thức thanh toán tiện lợi.</p><p><strong>Các phương thức thanh toán nào được chấp nhận?</strong><br>Chúng tôi chấp nhận thanh toán khi nhận hàng (COD), chuyển khoản ngân hàng, ví điện tử và cổng thanh toán tự động PayOS.</p><h3>Giao hàng &amp; Đổi trả</h3><p><strong>Thời gian giao hàng bao lâu?</strong><br>Thời gian giao hàng nội thành 2-3 ngày, các tỉnh khác từ 3-5 ngày làm việc.</p><p><strong>Chính sách đổi trả như thế nào?</strong><br>Bạn có thể đổi trả sản phẩm trong vòng 30 ngày nếu sản phẩm còn nguyên tem mác, chưa qua sử dụng và kèm hóa đơn mua hàng.</p>', NULL, 'Câu hỏi thường gặp (FAQ) - Thuong Lo', 'Tổng hợp và giải đáp các câu hỏi thường gặp về mua sắm, thanh toán, vận chuyển và đổi trả hàng tại Thuong Lo.'),
('shopping_guide', 'Hướng dẫn mua hàng', '<h2>Hướng dẫn đặt mua hàng tại Thuong Lo</h2><p>Chào mừng bạn đến với Thuong Lo! Nhằm giúp bạn có trải nghiệm mua sắm dễ dàng, thuận tiện nhất, dưới đây là hướng dẫn các bước đặt mua hàng nhanh chóng:</p><ol><li><strong>Bước 1: Tìm kiếm sản phẩm</strong> - Sử dụng thanh tìm kiếm hoặc duyệt qua danh mục sản phẩm, thương hiệu để tìm sản phẩm mong muốn.</li><li><strong>Bước 2: Thêm vào giỏ hàng</strong> - Chọn số lượng và nhấp vào nút "Thêm vào giỏ" hoặc click "Mua ngay".</li><li><strong>Bước 3: Điền thông tin giao nhận</strong> - Nhập chính xác tên, số điện thoại, địa chỉ nhận hàng để đảm bảo giao hàng chính xác.</li><li><strong>Bước 4: Chọn phương thức thanh toán</strong> - Chọn COD, quét mã chuyển khoản QR PayOS hoặc thẻ ngân hàng.</li><li><strong>Bước 5: Xác nhận đơn hàng</strong> - Bấm nút "Đặt hàng" để hoàn tất quy trình mua sắm. Đơn hàng của bạn sẽ được kích hoạt xử lý tự động trong tích tắc.</li></ol>', NULL, 'Hướng dẫn đặt mua hàng nhanh chóng - Thuong Lo', 'Hướng dẫn chi tiết các bước đặt mua hàng, thanh toán và kiểm tra tình trạng đơn hàng tại Thuong Lo.'),
('terms', 'Điều khoản dịch vụ', '<h2>Điều khoản dịch vụ và chính sách sử dụng</h2><p>Chào mừng bạn đến với hệ thống ThuongLo.com. Khi bạn truy cập, đăng ký tài khoản hoặc sử dụng dịch vụ của chúng tôi, đồng nghĩa với việc bạn đồng ý tuân thủ các điều khoản dịch vụ dưới đây:</p><h3>1. Tài khoản Người dùng</h3><p>Bạn chịu trách nhiệm bảo mật tài khoản và mật khẩu của mình. Mọi hoạt động phát sinh dưới tài khoản của bạn sẽ thuộc trách nhiệm cá nhân của bạn.</p><h3>2. Sở hữu trí tuệ</h3><p>Tất cả nội dung, gói dữ liệu nhà cung cấp, hình ảnh, mã nguồn và hệ thống tự động hóa thuộc quyền sở hữu trí tuệ độc quyền của ThuongLo. Nghiêm cấm mọi hành vi sao chép, phân phối hoặc bán lại khi chưa được sự đồng ý bằng văn bản của ban quản trị.</p><h3>3. Giới hạn trách nhiệm</h3><p>Chúng tôi luôn nỗ lực đảm bảo độ chính xác cao nhất của thông tin, tuy nhiên không chịu trách nhiệm trước bất kỳ tổn thất gián tiếp nào phát sinh do quá trình sử dụng dữ liệu.</p>', NULL, 'Điều khoản dịch vụ & Quy chế hoạt động - Thuong Lo', 'Đọc kỹ các quy định, điều khoản dịch vụ và chính sách sử dụng đối với khách hàng và đại lý khi tham gia Thuong Lo.'),
('privacy', 'Chính sách bảo mật', '<h2>Chính sách bảo mật thông tin cá nhân</h2><p>Thuong Lo cam kết bảo vệ tuyệt đối thông tin cá nhân của người dùng. Chính sách bảo mật dưới đây làm rõ cách thức chúng tôi thu thập, sử dụng và bảo vệ thông tin của bạn:</p><h3>1. Thu thập thông tin</h3><p>Chúng tôi thu thập thông tin khi bạn đăng ký tài khoản, đặt mua gói dữ liệu hoặc đăng ký làm đại lý (gồm Tên, Email, Số điện thoại và thông tin thanh toán phục vụ rút tiền qua PayOS).</p><h3>2. Sử dụng thông tin</h3><p>Thông tin thu thập được sử dụng để xử lý đơn hàng, gửi thông báo kích hoạt, hỗ trợ xử lý giao nhận logistics, và gửi ưu đãi khuyến mãi định kỳ (nếu bạn đồng ý nhận).</p><h3>3. Bảo mật dữ liệu</h3><p>Chúng tôi sử dụng giao thức mã hóa dữ liệu SSL bảo mật cao và lưu trữ dữ liệu trên máy chủ an toàn. Cam kết không chia sẻ, mua bán thông tin cá nhân của bạn cho bên thứ ba dưới bất kỳ hình thức nào.</p>', NULL, 'Chính sách bảo mật thông tin khách hàng - Thuong Lo', 'Cam kết bảo mật tuyệt đối dữ liệu và thông tin cá nhân của khách hàng khi tham gia giao dịch trên hệ thống Thuong Lo.'),
('footer_socials', 'Mạng xã hội Footer', '{"facebook":{"name":"Facebook","url":"https://facebook.com","visible":true,"icon":"fab fa-facebook"},"youtube":{"name":"Youtube","url":"https://youtube.com","visible":true,"icon":"fab fa-youtube"},"instagram":{"name":"Instagram","url":"https://instagram.com","visible":true,"icon":"fab fa-instagram"},"twitter":{"name":"X (Twitter)","url":"https://twitter.com","visible":true,"icon":"fab fa-twitter"},"tiktok":{"name":"Tiktok","url":"https://tiktok.com","visible":true,"icon":"fab fa-tiktok"},"linkedin":{"name":"Linkedin","url":"https://linkedin.com","visible":true,"icon":"fab fa-linkedin"}}', NULL, 'Social Connections', 'Footer social media icon connections configurations.')
ON DUPLICATE KEY UPDATE title=VALUES(title);
